# Менять разрешенно только значения, сам конфиг желательно не трогать

# Настрйоки сервиса который будет разворачиваться 
smart-glove-touch:
  ip-addres: "127.0.0.1"
  port: 8000

# Дальнейший обработчик пакетов, то есть следующий микросервис
service-gateway: 
  ip-addres: "127.0.0.1"
  port: 8001

web-soket-endpoint:
  imu: "/ws/imu"
  emg: "/ws/emg"
  site: "TODO"