# !! Менять разрешенно только значения, сам конфиг желательно не трогать !!

# Настрйоки сервиса который будет разворачиваться 
smart-glove-touch:
  ip-addres: "127.0.0.1"
  port-ws: 8000
  port-grpc: 8001
  max-workers: 10
  # Какой протокол будт использоваться для передачи данных с контроллера "ws" or "udp"
  protocol: "ws"

# Дальнейший обработчик пакетов, то есть следующий микросервис

web-soket-endpoint:
  imu: "/ws/imu"
  emg: "/ws/emg"
  site: "TODO"

# Ванильная версия crc16 - crc16-xmodem
